# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'planner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_planner_app(object):
    def setupUi(self, planner_app):
        planner_app.setObjectName("planner_app")
        planner_app.resize(854, 480)
        planner_app.setMinimumSize(QtCore.QSize(854, 480))
        planner_app.setMaximumSize(QtCore.QSize(854, 480))
        self.centralwidget = QtWidgets.QWidget(planner_app)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_image = QtWidgets.QLabel(self.centralwidget)
        self.bg_image.setGeometry(QtCore.QRect(0, 0, 861, 481))
        self.bg_image.setText("")
        self.bg_image.setPixmap(QtGui.QPixmap(":/Images/sunset_ocean.png"))
        self.bg_image.setScaledContents(True)
        self.bg_image.setObjectName("bg_image")
        self.bg_overlay = QtWidgets.QLabel(self.centralwidget)
        self.bg_overlay.setGeometry(QtCore.QRect(0, 0, 861, 481))
        self.bg_overlay.setText("")
        self.bg_overlay.setPixmap(QtGui.QPixmap(":/Images/bg_overlay2.png"))
        self.bg_overlay.setScaledContents(True)
        self.bg_overlay.setObjectName("bg_overlay")
        self.application_hotbar = QtWidgets.QLabel(self.centralwidget)
        self.application_hotbar.setGeometry(QtCore.QRect(0, 0, 861, 41))
        self.application_hotbar.setText("")
        self.application_hotbar.setObjectName("application_hotbar")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color:rgb(255, 255, 255);")
        self.title.setObjectName("title")
        self.minimize_button = QtWidgets.QPushButton(self.centralwidget)
        self.minimize_button.setGeometry(QtCore.QRect(755, 10, 42, 21))
        self.minimize_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize_button.setStyleSheet("QPushButton{\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(180, 180, 180, 140);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(180, 180, 180, 140);\n"
"    border-style: inset;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/78742/horizontal-line\">minimize</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        self.minimize_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icons8-minimize-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon)
        self.minimize_button.setObjectName("minimize_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(802, 10, 42, 21))
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255, 0, 0, 140);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(255, 0, 0, 140);\n"
"    border-style: inset;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/46/close\">Close</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        self.exit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/icons8-close-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon1)
        self.exit_button.setObjectName("exit_button")
        self.list_widget_holder = QtWidgets.QLabel(self.centralwidget)
        self.list_widget_holder.setGeometry(QtCore.QRect(354, 56, 485, 409))
        self.list_widget_holder.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgba(255, 160, 30, 120);\n"
"    border-radius: 10px;\n"
"}")
        self.list_widget_holder.setText("")
        self.list_widget_holder.setObjectName("list_widget_holder")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(15, 56, 324, 205))
        self.calendarWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarWidget.setObjectName("calendarWidget")
        self.todo_list_button = QtWidgets.QPushButton(self.centralwidget)
        self.todo_list_button.setGeometry(QtCore.QRect(69, 276, 216, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.todo_list_button.setFont(font)
        self.todo_list_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.todo_list_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(221, 142, 147);\n"
"\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/13462/to-do\">To Do</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/icons8-to-do-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.todo_list_button.setIcon(icon2)
        self.todo_list_button.setObjectName("todo_list_button")
        self.events_button = QtWidgets.QPushButton(self.centralwidget)
        self.events_button.setGeometry(QtCore.QRect(69, 317, 216, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.events_button.setFont(font)
        self.events_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.events_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(150, 171, 189);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/g0jrgxI2JR5l/event-accepted\">Events</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/icons8-events-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.events_button.setIcon(icon3)
        self.events_button.setObjectName("events_button")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(369, 71, 455, 379))
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background-color: rgba(255, 160, 30, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.todo_list_widget = QtWidgets.QListWidget(self.page)
        self.todo_list_widget.setGeometry(QtCore.QRect(0, 51, 455, 274))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.todo_list_widget.setFont(font)
        self.todo_list_widget.setStyleSheet("QListWidget{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    selection-background-color: rgba(221, 142, 147, 150);\n"
"    background-color: rgba(255, 160, 30, 120);\n"
"    border-radius: 10px;\n"
"}")
        self.todo_list_widget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todo_list_widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todo_list_widget.setObjectName("todo_list_widget")
        self.todo_date_label = QtWidgets.QLabel(self.page)
        self.todo_date_label.setGeometry(QtCore.QRect(0, 15, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.todo_date_label.setFont(font)
        self.todo_date_label.setStyleSheet("color:rgb(255, 255, 255);")
        self.todo_date_label.setObjectName("todo_date_label")
        self.add_todo_btn = QtWidgets.QPushButton(self.page)
        self.add_todo_btn.setGeometry(QtCore.QRect(0, 338, 103, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_todo_btn.setFont(font)
        self.add_todo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_todo_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(150, 171, 189);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/nkplpFWWQEKZ/add\">Add</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/icons8-add-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_todo_btn.setIcon(icon4)
        self.add_todo_btn.setObjectName("add_todo_btn")
        self.complete_todo_btn = QtWidgets.QPushButton(self.page)
        self.complete_todo_btn.setGeometry(QtCore.QRect(118, 338, 102, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.complete_todo_btn.setFont(font)
        self.complete_todo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.complete_todo_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(221, 142, 147);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/O9gFFs8Wy3Cf/pass\">Complete</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/icons8-complete-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.complete_todo_btn.setIcon(icon5)
        self.complete_todo_btn.setObjectName("complete_todo_btn")
        self.delete_todo_btn = QtWidgets.QPushButton(self.page)
        self.delete_todo_btn.setGeometry(QtCore.QRect(235, 338, 103, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_todo_btn.setFont(font)
        self.delete_todo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_todo_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(150, 171, 189);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/102350/delete\">Delete</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/icons8-delete-100(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_todo_btn.setIcon(icon6)
        self.delete_todo_btn.setObjectName("delete_todo_btn")
        self.delete_all_todo_btn = QtWidgets.QPushButton(self.page)
        self.delete_all_todo_btn.setGeometry(QtCore.QRect(352, 338, 102, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_all_todo_btn.setFont(font)
        self.delete_all_todo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_all_todo_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(221, 142, 147);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/102350/delete\">Delete</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/icons8-delete-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_all_todo_btn.setIcon(icon7)
        self.delete_all_todo_btn.setObjectName("delete_all_todo_btn")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.add_event_button = QtWidgets.QPushButton(self.page_2)
        self.add_event_button.setGeometry(QtCore.QRect(0, 338, 142, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_event_button.setFont(font)
        self.add_event_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_event_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(221, 142, 147);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/nkplpFWWQEKZ/add\">Add</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        self.add_event_button.setIcon(icon4)
        self.add_event_button.setObjectName("add_event_button")
        self.delete_all_events_btn = QtWidgets.QPushButton(self.page_2)
        self.delete_all_events_btn.setGeometry(QtCore.QRect(313, 338, 142, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_all_events_btn.setFont(font)
        self.delete_all_events_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_all_events_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(221, 142, 147);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/102350/delete\">Delete</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        self.delete_all_events_btn.setIcon(icon7)
        self.delete_all_events_btn.setObjectName("delete_all_events_btn")
        self.delete_event_button = QtWidgets.QPushButton(self.page_2)
        self.delete_event_button.setGeometry(QtCore.QRect(157, 338, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_event_button.setFont(font)
        self.delete_event_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_event_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(150, 171, 189);\n"
"    border-radius: 12px;\n"
"}\n"
"<a target=\"_blank\" href=\"https://icons8.com/icon/102350/delete\">Delete</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>")
        self.delete_event_button.setIcon(icon6)
        self.delete_event_button.setObjectName("delete_event_button")
        self.events_list_widget = QtWidgets.QListWidget(self.page_2)
        self.events_list_widget.setGeometry(QtCore.QRect(0, 51, 455, 274))
        self.events_list_widget.setStyleSheet("QListWidget{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    selection-background-color: rgba(221, 142, 147, 150);\n"
"    background-color: rgba(255, 160, 30, 120);\n"
"    border-radius: 10px;\n"
"}")
        self.events_list_widget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.events_list_widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.events_list_widget.setObjectName("events_list_widget")
        self.events_date_label = QtWidgets.QLabel(self.page_2)
        self.events_date_label.setGeometry(QtCore.QRect(0, 15, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.events_date_label.setFont(font)
        self.events_date_label.setStyleSheet("color:rgb(255, 255, 255);")
        self.events_date_label.setObjectName("events_date_label")
        self.stackedWidget.addWidget(self.page_2)
        planner_app.setCentralWidget(self.centralwidget)
        self.actionAdd_Task = QtWidgets.QAction(planner_app)
        self.actionAdd_Task.setIcon(icon4)
        self.actionAdd_Task.setObjectName("actionAdd_Task")
        self.actionComplete_Task = QtWidgets.QAction(planner_app)
        self.actionComplete_Task.setIcon(icon5)
        self.actionComplete_Task.setObjectName("actionComplete_Task")
        self.actionDelete_Selected_Task = QtWidgets.QAction(planner_app)
        self.actionDelete_Selected_Task.setIcon(icon6)
        self.actionDelete_Selected_Task.setObjectName("actionDelete_Selected_Task")
        self.actionDelete_All_Tasks = QtWidgets.QAction(planner_app)
        self.actionDelete_All_Tasks.setIcon(icon7)
        self.actionDelete_All_Tasks.setObjectName("actionDelete_All_Tasks")
        self.actionAdd_Event = QtWidgets.QAction(planner_app)
        self.actionAdd_Event.setIcon(icon4)
        self.actionAdd_Event.setObjectName("actionAdd_Event")
        self.actionDelete_Selected_Event = QtWidgets.QAction(planner_app)
        self.actionDelete_Selected_Event.setIcon(icon6)
        self.actionDelete_Selected_Event.setObjectName("actionDelete_Selected_Event")
        self.actionDelete_All_Events = QtWidgets.QAction(planner_app)
        self.actionDelete_All_Events.setIcon(icon7)
        self.actionDelete_All_Events.setObjectName("actionDelete_All_Events")

        self.retranslateUi(planner_app)
        self.stackedWidget.setCurrentIndex(0)
        self.exit_button.clicked.connect(planner_app.close) # type: ignore
        self.minimize_button.clicked.connect(planner_app.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(planner_app)

    def retranslateUi(self, planner_app):
        _translate = QtCore.QCoreApplication.translate
        planner_app.setWindowTitle(_translate("planner_app", "Planner Application"))
        self.title.setText(_translate("planner_app", "Planner Application"))
        self.todo_list_button.setText(_translate("planner_app", "To Do List"))
        self.events_button.setText(_translate("planner_app", "Events"))
        self.todo_date_label.setText(_translate("planner_app", "Todo: Date Goes Here"))
        self.add_todo_btn.setText(_translate("planner_app", "Add Task"))
        self.complete_todo_btn.setText(_translate("planner_app", "Complete"))
        self.delete_todo_btn.setText(_translate("planner_app", "Delete"))
        self.delete_all_todo_btn.setText(_translate("planner_app", "Delete All"))
        self.add_event_button.setText(_translate("planner_app", "Add Event"))
        self.delete_all_events_btn.setText(_translate("planner_app", "Delete All"))
        self.delete_event_button.setText(_translate("planner_app", "Delete"))
        self.events_date_label.setText(_translate("planner_app", "Events: Date Goes Here"))
        self.actionAdd_Task.setText(_translate("planner_app", "Add Task"))
        self.actionAdd_Task.setToolTip(_translate("planner_app", "Add Task"))
        self.actionComplete_Task.setText(_translate("planner_app", "Complete Task"))
        self.actionComplete_Task.setToolTip(_translate("planner_app", "Complete Task"))
        self.actionDelete_Selected_Task.setText(_translate("planner_app", "Delete Selected Task"))
        self.actionDelete_Selected_Task.setToolTip(_translate("planner_app", "Delete Selected Task"))
        self.actionDelete_All_Tasks.setText(_translate("planner_app", "Delete All Tasks"))
        self.actionDelete_All_Tasks.setToolTip(_translate("planner_app", "Delete All Tasks"))
        self.actionAdd_Event.setText(_translate("planner_app", "Add Event"))
        self.actionAdd_Event.setToolTip(_translate("planner_app", "Add Event"))
        self.actionDelete_Selected_Event.setText(_translate("planner_app", "Delete Selected  Event"))
        self.actionDelete_Selected_Event.setToolTip(_translate("planner_app", "Delete Selected Event"))
        self.actionDelete_All_Events.setText(_translate("planner_app", "Delete All Events"))
        self.actionDelete_All_Events.setToolTip(_translate("planner_app", "Delete All Events"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    planner_app = QtWidgets.QMainWindow()
    ui = Ui_planner_app()
    ui.setupUi(planner_app)
    planner_app.show()
    sys.exit(app.exec_())
